# Generated by Django 4.2.17 on 2024-12-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.category'),
        ),
    ]
