# Generated by Django 4.2.17 on 2024-12-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_products_category_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.category'),
        ),
    ]
